image:
  file: .gitpod.Dockerfile

tasks:
- init: |
    mkdir -p build && cd build
    cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DWITH_XC_ALL=ON
    make
  command: echo 'start script'